import "./globals.css";
import Navigation from "./Components/Navigation";
import WelcomeScreen from "./Components/WelcomeScreen";
import Footer from "./Components/Footer";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Better Together Charcuterie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WelcomeScreen />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
